services:

  kong-db:
    image: postgres:17
    container_name: kong-db
    restart: always
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: oquequehavelhinho15$
      POSTGRES_DB: kong_db
    volumes:
      - kong_db_data:/var/lib/postgresql/data
    networks:
      - workshop-net
    ports:
      - '5434:5432'

  kong-migrations:
    image: kong:latest
    container_name: kong-migrations
    restart: on-failure
    command: 'kong migrations bootstrap'
    depends_on:
      - kong-db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: oquequehavelhinho15$
      KONG_PG_DATABASE: kong_db
    networks:
      - workshop-net

  kong-gateway:
    image: kong:latest
    container_name: kong-gateway
    restart: always
    depends_on:
      - kong-migrations
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: oquequehavelhinho15$
      KONG_PG_DATABASE: kong_db
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
    ports:
      - '8000:8000'
      - '8443:8443'
      - '8001:8001'
      - '8002:8002'
      - '8444:8444'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - workshop-net

networks:
  workshop-net:
    external: true
    name: workshop-net
    driver: bridge

volumes:
  kong_db_data:
  sonarqube_db_data:
  sonarqube_extensions:
  sonarqube_logs:
  nexus-data: